name: Latest issue created
on:
    issues:
        type: opened
jobs:
    check_latest_issue_created:
        runs-on: ubuntu-latest
        steps:
        -   name: Get and save date
            run: echo "DATE=$(TZ=Europe/Belgrade date +'%d.%m.%y %H:%M %Z')" >> $GITHUB_ENV
        -   name: Update GitHub README
            uses: theboi/github-update-readme@v1.3.0
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
                header: "test1"
                subhead: "Latest opened issue [#${{ github.event.issue.number }}](https://github.com/nbakotic/GameProject/issues/${{ github.event.issue.number }}) (${{ github.event.issue.title }})."
                footer: "Opened by [${{ github.actor }}](https://github.com/${{ github.actor }}) on ${{ env.DATE }}."
                header: "test2"
                repoCount: 0